accounts:
  account_1:
    username: jispotalte
    password: HU5uFQ3gcPhGME
    usermail: jispotalte@gufum.com
  account_2:
    username: raydenikno
    password: pzKXRppFNJ5y8u
    usermail: raydenikno@gufum.com
  account_3:
    username: bostugesta
    password: cZEpXy2Lekifa2
    usermail: bostugesta@gufum.com